apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: confluent-proxy
data:
  nginx.conf: |-
    events {}

    stream {
        map $ssl_preread_server_name $targetBackend {
          default $ssl_preread_server_name;
      }

      server {
        listen 9092;

        proxy_connect_timeout 1s;
        proxy_timeout 3s;
        resolver 169.254.169.253;

        proxy_pass $targetBackend:9092;
        ssl_preread on;

      }

      server {
        listen 443;

        proxy_connect_timeout 1s;
        proxy_timeout 3s;
        resolver 169.254.169.253;

        proxy_pass $targetBackend:443;
        ssl_preread on;
      }
    }