all:
  vars:
    ansible_become: true
    ansible_connection: ssh
    ansible_user: ubuntu

    kafka_broker_custom_properties:
      confluent.log.placement.constraints: '{"version":2,"replicas":[{"count":2,"constraints":{"rack":"ap-southeast-1"}},{"count":2,"constraints":{"rack":"ap-southeast-2"}}],"observers":[{"count":1,"constraints":{"rack":"ap-southeast-1"}},{"count":1,"constraints":{"rack":"ap-southeast-2"}}],"observerPromotionPolicy":"under-min-isr"}'
      min.insync.replicas: "3"
      replica.selector.class: org.apache.kafka.common.replica.RackAwareReplicaSelector

kafka_controller:
  hosts:
    ip-10-41-1-10.ap-southeast-1.compute.internal:
    ip-10-41-2-10.ap-southeast-1.compute.internal:
    ip-10-41-3-10.ap-southeast-1.compute.internal:
    ip-10-42-1-10.ap-southeast-2.compute.internal:
    ip-10-42-2-10.ap-southeast-2.compute.internal:
kafka_broker:
  children:
    kafka_broker_r0:
    kafka_broker_r1:

kafka_broker_r0:
  vars:
    kafka_broker_custom_properties:
      broker.rack: ap-southeast-1

  hosts:
    ip-10-41-1-10.ap-southeast-1.compute.internal:
    ip-10-41-1-11.ap-southeast-1.compute.internal:
    ip-10-41-2-10.ap-southeast-1.compute.internal:
    ip-10-41-2-11.ap-southeast-1.compute.internal:
    ip-10-41-3-10.ap-southeast-1.compute.internal:
    ip-10-41-3-11.ap-southeast-1.compute.internal:

kafka_broker_r1:
  vars:
    kafka_broker_custom_properties:
      broker.rack: ap-southeast-2

  hosts:
    ip-10-42-1-10.ap-southeast-2.compute.internal:
    ip-10-42-1-11.ap-southeast-2.compute.internal:
    ip-10-42-2-10.ap-southeast-2.compute.internal:
    ip-10-42-2-11.ap-southeast-2.compute.internal:
    ip-10-42-3-10.ap-southeast-2.compute.internal:
    ip-10-42-3-11.ap-southeast-2.compute.internal:

